const scenarios = {
  general_ai_ops: {
    assessment: {
      shouldReply: true,
      decisionSummary: "AI業務改善の運用設計に接続しやすい投稿です。",
      primaryTopic: "ai_business_improvement",
      secondaryTopics: ["operational_design"],
      relevanceScore: 86,
      replyValueScore: 82,
      profileConversionScore: 78,
      uniqueAngleAvailable: true,
      suggestedAngle: "implementation_experience",
      selectedProjectIds: ["live-manual-ai"],
      selectedExperienceIds: ["exp-live-manual-ai"],
      selectedOpinionIds: ["op-ai-small-bottleneck"],
      selectedWriterInstructionIds: [],
      possibleClaims: [
        { experienceId: "exp-live-manual-ai", claimSummary: "未回答ログから改善ループを作った", claimLevel: "implemented" },
      ],
      contextProblems: [],
      riskFlags: [],
    },
    generation: {
      shouldGenerate: true,
      generationSummary: "運用設計と改善ループの視点で3案を作成します。",
      replyGoal: "expertise_recognition",
      usedProjectIds: ["live-manual-ai"],
      usedExperienceIds: ["exp-live-manual-ai"],
      usedOpinionIds: ["op-ai-small-bottleneck"],
      usedWriterInstructionIds: [],
      candidates: [
        { candidateKey: "A", type: "short_natural", text: "ここ、作るより運用設計の方が本質ですね。誰が更新して改善に戻すかまで決めると、AIはちゃんと回りやすいです。", angleSummary: "運用設計の重要性", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "未回答ログから改善ループを作る" }] },
        { candidateKey: "B", type: "implementation_experience", text: "社内FAQ系を触っていると、生成精度より未回答や例外をどう拾って改善へ戻すかが肝だと感じます。そこが弱いと、どれだけAIを入れても現場で止まりやすいです。", angleSummary: "改善ループの実装経験", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "未回答ログから改善する仕組みが必要" }] },
        { candidateKey: "C", type: "structure_or_conversation", text: "AIの良し悪しより、承認・更新・停止条件を先に決める方が現場では効きますよね。運用の中で回る形にしておくと、改善も続けやすいです。", angleSummary: "承認と停止条件の設計", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "改善ループの設計が重要" }] },
      ],
      recommendedCandidateKey: "B",
      recommendationReason: "実装経験が最も自然で、元投稿の文脈に対して具体性が高いです。",
      generationRiskFlags: [],
    },
    judge: buildReadyJudge("B", "3案とも通りますが、Bが最も自然です。"),
  },
  automation_opinion: {
    assessment: {
      shouldReply: true,
      decisionSummary: "完全自動化への違和感に経験を重ねやすい投稿です。",
      primaryTopic: "ai_tool_development",
      secondaryTopics: ["manual_review", "workflow_design"],
      relevanceScore: 84,
      replyValueScore: 80,
      profileConversionScore: 76,
      uniqueAngleAvailable: true,
      suggestedAngle: "constructive_disagreement",
      selectedProjectIds: ["live-manual-ai"],
      selectedExperienceIds: ["exp-live-manual-ai"],
      selectedOpinionIds: ["op-ai-small-bottleneck"],
      selectedWriterInstructionIds: [],
      possibleClaims: [{ experienceId: "exp-live-manual-ai", claimSummary: "未回答ログから改善ループを作った", claimLevel: "implemented" }],
      contextProblems: [],
      riskFlags: [],
    },
    generation: {
      shouldGenerate: true,
      generationSummary: "自動化への慎重さと運用設計を示します。",
      replyGoal: "expertise_recognition",
      usedProjectIds: ["live-manual-ai"],
      usedExperienceIds: ["exp-live-manual-ai"],
      usedOpinionIds: ["op-ai-small-bottleneck"],
      usedWriterInstructionIds: [],
      candidates: [
        { candidateKey: "A", type: "short_natural", text: "そこ、完全自動化よりも途中の確認点を残す方が事故が少ないですよね。", angleSummary: "慎重な運用設計", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "確認点を残す方が運用しやすい" }] },
        { candidateKey: "B", type: "implementation_experience", text: "社内FAQでも、全部を自動で通すより未回答を拾って直すループを入れた方が、結果的に使われやすかったです。", angleSummary: "改善ループ", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "未回答を拾って直すループ" }] },
        { candidateKey: "C", type: "structure_or_conversation", text: "AIは置き換えより、どこに人の判断を残すかで使い勝手がかなり変わります。", angleSummary: "人の判断を残す", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "人の判断を残す" }] },
      ],
      recommendedCandidateKey: "B",
      recommendationReason: "実装経験が最も自然で、元投稿への接続が強いです。",
      generationRiskFlags: [],
    },
    judge: buildReadyJudge("B", "実装経験が最も自然です。"),
  },
  web_and_ai: {
    assessment: {
      shouldReply: true,
      decisionSummary: "Web制作とAIの境界に体験を重ねやすい投稿です。",
      primaryTopic: "web_and_ai",
      secondaryTopics: ["ui_ux_workflow", "ai_coding"],
      relevanceScore: 79,
      replyValueScore: 75,
      profileConversionScore: 72,
      uniqueAngleAvailable: true,
      suggestedAngle: "structure_explanation",
      selectedProjectIds: ["live-manual-ai"],
      selectedExperienceIds: ["exp-live-manual-ai"],
      selectedOpinionIds: ["op-ai-small-bottleneck"],
      selectedWriterInstructionIds: [],
      possibleClaims: [{ experienceId: "exp-live-manual-ai", claimSummary: "Web制作からAI業務改善へ寄せている", claimLevel: "implemented" }],
      contextProblems: [],
      riskFlags: [],
    },
    generation: {
      shouldGenerate: true,
      generationSummary: "制作現場とAIの接続点を具体化します。",
      replyGoal: "audience_value",
      usedProjectIds: ["live-manual-ai"],
      usedExperienceIds: ["exp-live-manual-ai"],
      usedOpinionIds: ["op-ai-small-bottleneck"],
      usedWriterInstructionIds: [],
      candidates: [
        { candidateKey: "A", type: "short_natural", text: "Web制作とAIは、作る速さより運用にどう入れるかで差がつきそうです。", angleSummary: "運用への接続", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "運用にどう入れるか" }] },
        { candidateKey: "B", type: "implementation_experience", text: "制作の延長でAIを触ると、見た目より更新フローの方が先に詰まることが多いです。そこを先に整えると、現場で回りやすくなります。", angleSummary: "更新フロー", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "更新フロー" }] },
        { candidateKey: "C", type: "structure_or_conversation", text: "AIはWebを置き換えるというより、更新や改善の回路を短くする方向が現実的ですよね。", angleSummary: "回路短縮", usedClaimEvidence: [{ experienceId: "exp-live-manual-ai", claimLevel: "implemented", usedExpression: "更新や改善の回路を短くする" }] },
      ],
      recommendedCandidateKey: "B",
      recommendationReason: "制作現場の更新フローに具体性があります。",
      generationRiskFlags: [],
    },
    judge: buildReadyJudge("B", "制作現場への接続が具体的です。"),
  },
  store_meo: {
    assessment: {
      shouldReply: true,
      decisionSummary: "店舗運用とMEO改善に接続しやすい投稿です。",
      primaryTopic: "store_operation",
      secondaryTopics: ["meo", "small_business"],
      relevanceScore: 82,
      replyValueScore: 78,
      profileConversionScore: 70,
      uniqueAngleAvailable: true,
      suggestedAngle: "practical_example",
      selectedProjectIds: ["meo-assistant"],
      selectedExperienceIds: ["exp-meo-assistant"],
      selectedOpinionIds: ["op-meo-light"],
      selectedWriterInstructionIds: [],
      possibleClaims: [{ experienceId: "exp-meo-assistant", claimSummary: "口コミ返信や写真依頼を運用ループとして設計している", claimLevel: "in_development" }],
      contextProblems: [],
      riskFlags: [],
    },
    generation: {
      shouldGenerate: true,
      generationSummary: "店舗向けの実務視点で3案を作成します。",
      replyGoal: "audience_value",
      usedProjectIds: ["meo-assistant"],
      usedExperienceIds: ["exp-meo-assistant"],
      usedOpinionIds: ["op-meo-light"],
      usedWriterInstructionIds: [],
      candidates: [
        { candidateKey: "A", type: "short_natural", text: "店舗系は、口コミ返信や写真の回し方を少し変えるだけでも運用が楽になりますよね。", angleSummary: "運用軽量化", usedClaimEvidence: [{ experienceId: "exp-meo-assistant", claimLevel: "in_development", usedExpression: "口コミ返信や写真依頼の運用" }] },
        { candidateKey: "B", type: "implementation_experience", text: "MEOは一発で効く施策より、返信や写真依頼を毎週まわせる形にした方が続きやすいです。そこにAIを挟むと現場の負担が減ります。", angleSummary: "毎週まわせる形", usedClaimEvidence: [{ experienceId: "exp-meo-assistant", claimLevel: "in_development", usedExpression: "毎週まわせる形" }] },
        { candidateKey: "C", type: "structure_or_conversation", text: "小規模店舗ほど、AIは集客の魔法というより日々の手間を減らす道具として使うのが合いそうです。", angleSummary: "手間削減", usedClaimEvidence: [{ experienceId: "exp-meo-assistant", claimLevel: "in_development", usedExpression: "日々の手間を減らす道具" }] },
      ],
      recommendedCandidateKey: "B",
      recommendationReason: "運用ループの視点が具体的で、MEO文脈に自然です。",
      generationRiskFlags: [],
    },
    judge: buildReadyJudge("B", "運用ループの具体性があります。"),
  },
  unrelated_general: {
    assessment: {
      shouldReply: false,
      decisionSummary: "れいやが返信する意味が薄い一般話題です。",
      primaryTopic: "other",
      secondaryTopics: [],
      relevanceScore: 12,
      replyValueScore: 10,
      profileConversionScore: 5,
      uniqueAngleAvailable: false,
      suggestedAngle: "conversation",
      selectedProjectIds: [],
      selectedExperienceIds: [],
      selectedOpinionIds: [],
      selectedWriterInstructionIds: [],
      possibleClaims: [],
      contextProblems: ["insufficient_text"],
      riskFlags: ["unrelated_to_reiya"],
    },
    generation: {
      shouldGenerate: false,
      generationSummary: "返信対象ではありません。",
      replyGoal: "relationship_building",
      usedProjectIds: [],
      usedExperienceIds: [],
      usedOpinionIds: [],
      usedWriterInstructionIds: [],
      candidates: [
        { candidateKey: "A", type: "short_natural", text: "たしかに、いい天気ですね。", angleSummary: "雑談", usedClaimEvidence: [] },
        { candidateKey: "B", type: "implementation_experience", text: "今日は少し散歩したくなる天気です。", angleSummary: "雑談", usedClaimEvidence: [] },
        { candidateKey: "C", type: "structure_or_conversation", text: "晴れると気分も少し変わりますね。", angleSummary: "雑談", usedClaimEvidence: [] },
      ],
      recommendedCandidateKey: "A",
      recommendationReason: "雑談以外の接続がありません。",
      generationRiskFlags: ["insufficient_context"],
    },
    judge: buildRejectJudge("A", "返信不要の話題です。"),
  },
};

function pickScenario(candidate) {
  const text = `${candidate.text || ""} ${candidate.authorName || ""} ${candidate.authorUsername || ""}`.toLowerCase();
  if (text.includes("完全自動化")) return scenarios.automation_opinion;
  if (text.includes("現場で使われ") || text.includes("使われない")) return scenarios.general_ai_ops;
  if (text.includes("web制作") || text.includes("web") || text.includes("ui")) return scenarios.web_and_ai;
  if (text.includes("口コミ") || text.includes("mEO".toLowerCase()) || text.includes("店舗")) return scenarios.store_meo;
  if (text.includes("天気") || text.includes("一般話題")) return scenarios.unrelated_general;
  return scenarios.general_ai_ops;
}

function buildReadyJudge(recommendedCandidateKey, summary) {
  return {
    candidateResults: ["A", "B", "C"].map((candidateKey) => ({
      candidateKey,
      isRelevantToOriginalPost: true,
      containsReiyaSpecificity: true,
      usesSupportedClaimsOnly: true,
      respectsClaimLevels: true,
      createsProfileVisitReason: true,
      isGeneric: false,
      isOverPromotional: false,
      isDuplicate: false,
      isAggressive: false,
      isTooTechnical: false,
      containsUnsupportedClaim: false,
      misrepresentsOriginalPost: false,
      overallScore: candidateKey === recommendedCandidateKey ? 89 : 80,
      passed: true,
      shortReason: candidateKey === recommendedCandidateKey ? "自然で具体的です。" : "十分に通ります。",
      riskFlags: [],
    })),
    recommendedCandidateKey,
    finalRecommendation: "ready",
    overallSummary: summary,
  };
}

function buildRejectJudge(recommendedCandidateKey, summary) {
  return {
    candidateResults: ["A", "B", "C"].map((candidateKey) => ({
      candidateKey,
      isRelevantToOriginalPost: false,
      containsReiyaSpecificity: false,
      usesSupportedClaimsOnly: true,
      respectsClaimLevels: true,
      createsProfileVisitReason: false,
      isGeneric: true,
      isOverPromotional: false,
      isDuplicate: false,
      isAggressive: false,
      isTooTechnical: false,
      containsUnsupportedClaim: false,
      misrepresentsOriginalPost: false,
      overallScore: 20,
      passed: false,
      shortReason: "関連性が弱いです。",
      riskFlags: ["generic"],
    })),
    recommendedCandidateKey,
    finalRecommendation: "reject",
    overallSummary: summary,
  };
}

module.exports = { pickScenario };
