const { z } = require("zod");

const ClaimLevelSchema = z.enum(["verified", "implemented", "tested", "in_development", "planned", "opinion"]);

const ReplyCandidateSchema = z.object({
  candidateKey: z.enum(["A", "B", "C"]),
  text: z.string().min(20).max(220),
  usedClaimEvidence: z.array(z.object({
    experienceId: z.string(),
    claimLevel: ClaimLevelSchema,
    usedExpression: z.string().max(200),
  })).max(4),
  selfCheckFlags: z.array(z.enum([
    "generic",
    "overpromotion",
    "unsupported_claim",
    "duplicate_expression",
    "too_technical",
    "too_long",
    "too_aggressive",
    "insufficient_context",
    "claim_level_violation",
    "original_post_misread",
  ])).max(10),
});

const ReplyDecisionSchema = z.object({
  shouldReply: z.boolean(),
  decisionSummary: z.string().max(300),
  primaryTopic: z.enum([
    "ai_business_improvement",
    "ai_tool_development",
    "web_and_ai",
    "sns_operation",
    "x_operation",
    "threads_operation",
    "small_business",
    "store_operation",
    "meo",
    "internal_faq",
    "manual_and_knowledge",
    "sales_efficiency",
    "individual_development",
    "ai_coding",
    "ui_ux_workflow",
    "other",
  ]),
  scores: z.object({
    relevance: z.number().min(0).max(100),
    replyValue: z.number().min(0).max(100),
    profileConversion: z.number().min(0).max(100),
  }),
  selectedProjectIds: z.array(z.string()).max(2),
  selectedExperienceIds: z.array(z.string()).max(4),
  selectedOpinionIds: z.array(z.string()).max(4),
  selectedWriterInstructionIds: z.array(z.string()).max(5),
  riskFlags: z.array(z.enum([
    "political",
    "medical",
    "legal",
    "financial",
    "harassment",
    "misinformation",
    "adult",
    "violent",
    "religious",
    "personal_attack",
    "overpromotion_risk",
    "insufficient_context",
    "unrelated_to_reiya",
  ])).max(12),
  replies: z.object({
    A: ReplyCandidateSchema,
    B: ReplyCandidateSchema,
    C: ReplyCandidateSchema,
  }),
  recommendedCandidateKey: z.enum(["A", "B", "C"]),
  finalRecommendation: z.enum(["ready", "manual_review", "skip"]),
});

const CandidateAssessmentSchema = z.object({
  shouldReply: z.boolean(),
  decisionSummary: z.string().max(300),
  primaryTopic: z.enum([
    "ai_business_improvement",
    "ai_tool_development",
    "web_and_ai",
    "sns_operation",
    "x_operation",
    "threads_operation",
    "small_business",
    "store_operation",
    "meo",
    "internal_faq",
    "manual_and_knowledge",
    "sales_efficiency",
    "individual_development",
    "ai_coding",
    "ui_ux_workflow",
    "other",
  ]),
  secondaryTopics: z.array(z.string()).max(5),
  relevanceScore: z.number().min(0).max(100),
  replyValueScore: z.number().min(0).max(100),
  profileConversionScore: z.number().min(0).max(100),
  uniqueAngleAvailable: z.boolean(),
  suggestedAngle: z.enum([
    "agreement_plus_insight",
    "implementation_experience",
    "structure_explanation",
    "practical_example",
    "constructive_disagreement",
    "conversation",
  ]),
  selectedProjectIds: z.array(z.string()).max(2),
  selectedExperienceIds: z.array(z.string()).max(3),
  selectedOpinionIds: z.array(z.string()).max(3),
  selectedWriterInstructionIds: z.array(z.string()).max(5),
  possibleClaims: z.array(z.object({
    experienceId: z.string(),
    claimSummary: z.string(),
    claimLevel: z.enum(["verified", "implemented", "tested", "in_development", "planned", "opinion"]),
  })).max(5),
  contextProblems: z.array(z.enum([
    "missing_parent_post",
    "missing_quoted_post",
    "media_context_required",
    "insufficient_text",
    "ambiguous_target",
    "specialist_knowledge_required",
  ])).max(6),
  riskFlags: z.array(z.enum([
    "political",
    "medical",
    "legal",
    "financial",
    "harassment",
    "misinformation",
    "adult",
    "violent",
    "religious",
    "personal_attack",
    "overpromotion_risk",
    "insufficient_context",
    "unrelated_to_reiya",
  ])).max(12),
});

const ReplyGenerationSchema = z.object({
  shouldGenerate: z.boolean(),
  generationSummary: z.string().max(300),
  replyGoal: z.enum([
    "profile_visit",
    "author_conversation",
    "expertise_recognition",
    "audience_value",
    "relationship_building",
  ]),
  usedProjectIds: z.array(z.string()).max(2),
  usedExperienceIds: z.array(z.string()).max(3),
  usedOpinionIds: z.array(z.string()).max(3),
  usedWriterInstructionIds: z.array(z.string()).max(5),
  candidates: z.array(z.object({
    candidateKey: z.enum(["A", "B", "C"]),
    type: z.enum(["short_natural", "implementation_experience", "structure_or_conversation"]),
    text: z.string().min(20).max(220),
    angleSummary: z.string().max(200),
    usedClaimEvidence: z.array(z.object({
      experienceId: z.string(),
      claimLevel: z.enum(["verified", "implemented", "tested", "in_development", "planned", "opinion"]),
      usedExpression: z.string().max(200),
    })).max(4),
  })).length(3),
  recommendedCandidateKey: z.enum(["A", "B", "C"]),
  recommendationReason: z.string().max(250),
  generationRiskFlags: z.array(z.enum([
    "overpromotion",
    "generic",
    "unsupported_claim",
    "duplicate_expression",
    "too_technical",
    "too_long",
    "too_aggressive",
    "insufficient_context",
  ])).max(8),
});

const ReplyJudgeSchema = z.object({
  candidateResults: z.array(z.object({
    candidateKey: z.enum(["A", "B", "C"]),
    isRelevantToOriginalPost: z.boolean(),
    containsReiyaSpecificity: z.boolean(),
    usesSupportedClaimsOnly: z.boolean(),
    respectsClaimLevels: z.boolean(),
    createsProfileVisitReason: z.boolean(),
    isGeneric: z.boolean(),
    isOverPromotional: z.boolean(),
    isDuplicate: z.boolean(),
    isAggressive: z.boolean(),
    isTooTechnical: z.boolean(),
    containsUnsupportedClaim: z.boolean(),
    misrepresentsOriginalPost: z.boolean(),
    overallScore: z.number().min(0).max(100),
    passed: z.boolean(),
    shortReason: z.string().max(250),
    riskFlags: z.array(z.enum([
      "generic",
      "overpromotion",
      "duplicate",
      "aggressive",
      "too_technical",
      "unsupported_claim",
      "claim_level_violation",
      "original_post_misread",
      "insufficient_reiya_specificity",
      "weak_profile_conversion",
    ])).max(10),
  })).length(3),
  recommendedCandidateKey: z.enum(["A", "B", "C"]).nullable(),
  finalRecommendation: z.enum(["ready", "regenerate_once", "manual_review", "reject"]),
  overallSummary: z.string().max(300),
});

module.exports = {
  ClaimLevelSchema,
  ReplyCandidateSchema,
  ReplyDecisionSchema,
  CandidateAssessmentSchema,
  ReplyGenerationSchema,
  ReplyJudgeSchema,
};
