export const seedData = {
  creatorProfile: {
    profileId: "reiya-public-x",
    displayName: "れいちぇる｜Web×AIツール開発",
    handle: "Rachel_hkz",
    positioning:
      "Web制作出身のAI業務改善ツール開発者。AIの情報を紹介するだけではなく、実際の業務へ落とし込み、運用・改善まで実装する人。",
    targetAudiences: [
      "個人事業主",
      "小規模事業者",
      "店舗経営者",
      "Web制作者",
      "SNS運用担当者",
      "業務効率化を進めたい人",
    ],
    desiredPerception: [
      "実際にツールを作り現場で試している",
      "Web制作と業務理解の両方がある",
      "AIを現実的な仕組みに変えられる",
    ],
    coreSkills: ["React", "Vite", "Firebase", "OpenAI API", "Web制作", "業務フロー設計"],
    publicOnly: true,
    version: 1,
  },
  experiences: [
    {
      experienceId: "exp-live-manual-ai",
      projectId: "live-manual-ai",
      name: "Live Manual AI",
      title: "社内FAQ・マニュアルAI",
      description: "社内FAQ・マニュアル・業務ルールをAIが参照し、スタッフの質問へ回答するシステム",
      categories: ["社内FAQ", "マニュアル", "業務改善", "ナレッジ共有", "AIツール開発"],
      relatedKeywords: ["FAQ", "マニュアル", "未回答", "ナレッジ", "改善ループ"],
      claimLevel: "implemented",
      usableClaims: [
        "社内FAQは導入より情報更新と改善ループの設計が重要",
        "未回答ログからマニュアルを改善する仕組みが必要",
      ],
      prohibitedClaims: ["導入企業で成果が出た", "全社展開に成功した"],
      useForReply: true,
      useForOriginalPost: true,
      publicUseAllowed: true,
      priority: 1,
    },
    {
      experienceId: "exp-meo-assistant",
      projectId: "meo-assistant",
      name: "MEO運用アシスタント",
      title: "店舗向けMEO運用AI",
      description: "Googleビジネスプロフィールの投稿、口コミ返信、写真依頼、月次改善を支援するAIシステム",
      categories: ["店舗運営", "MEO", "Googleビジネスプロフィール", "業務自動化", "AIツール開発"],
      relatedKeywords: ["MEO", "店舗", "Googleビジネス", "口コミ", "写真依頼"],
      claimLevel: "in_development",
      usableClaims: [
        "MEO運用は投稿生成だけではなく、写真依頼や承認の業務ループが重要",
        "小規模店舗では小さな繰り返し作業の削減効果が大きい",
      ],
      prohibitedClaims: ["顧客店舗で成果を出した", "検索順位を改善した"],
      useForReply: true,
      useForOriginalPost: true,
      publicUseAllowed: true,
      priority: 2,
    },
    {
      experienceId: "exp-threads-ai",
      projectId: "threads-ai",
      name: "Threads運用AI",
      title: "SNS運用AI",
      description: "複数アカウントの戦略、投稿生成、承認、予約、実投稿、分析、改善を管理するSNS運用AI",
      categories: ["SNS運用", "Threads", "AI自動化", "投稿生成", "AIツール開発"],
      relatedKeywords: ["SNS", "Threads", "承認", "投稿分析", "Strategy"],
      claimLevel: "verified",
      usableClaims: [
        "SNS運用は投稿生成だけでは回らず、承認と投稿後分析まで必要",
        "完全自動より人間確認を残した半自動運用の方が安全",
      ],
      prohibitedClaims: ["大規模アカウントで成果を出した", "収益化した"],
      useForReply: true,
      useForOriginalPost: true,
      publicUseAllowed: true,
      priority: 3,
    },
    {
      experienceId: "exp-sales-researcher",
      projectId: "ai-sales-researcher",
      name: "営業リスト作成AI",
      title: "営業リサーチAI",
      description: "公式HPを検索・分析し、営業適性や個別営業文をGoogle Sheetsへ出力するシステム",
      categories: ["営業", "リサーチ", "AI業務改善", "Google Sheets"],
      relatedKeywords: ["営業", "リサーチ", "Sheets", "検索", "分析"],
      claimLevel: "implemented",
      usableClaims: [
        "営業自動化で重要なのは送信数より営業先選定",
        "自由生成より基本構造を固定して個別部分だけ変える方が安全",
      ],
      prohibitedClaims: ["受注につながった", "大量送信した"],
      useForReply: true,
      useForOriginalPost: true,
      publicUseAllowed: true,
      priority: 4,
    },
  ],
  opinions: [
    {
      opinionId: "op-ai-small-bottleneck",
      category: "AIツール開発",
      statement: "全部を自動化するより、1つのボトルネックを減らす方が成功しやすいです。",
      supportingExperienceIds: ["exp-live-manual-ai", "exp-meo-assistant"],
      tone: "practical",
      publicUseAllowed: true,
      isActive: true,
    },
    {
      opinionId: "op-approval-loop",
      category: "SNS運用",
      statement: "完全自動投稿より、人間承認を残した半自動運用の方が現実的です。",
      supportingExperienceIds: ["exp-threads-ai"],
      tone: "neutral",
      publicUseAllowed: true,
      isActive: true,
    },
    {
      opinionId: "op-ui-action-board",
      category: "Web制作×AI",
      statement: "管理画面はデータを見る場所ではなく、業務を前へ進める操作盤だと考えています。",
      supportingExperienceIds: ["exp-live-manual-ai", "exp-meo-assistant"],
      tone: "practical",
      publicUseAllowed: true,
      isActive: true,
    },
  ],
  writingRules: {
    ruleSetId: "sei-x-writing-v1",
    replyRules: {
      minCharacters: 60,
      maxCharacters: 180,
      requireOriginalPostConnection: true,
      maxProjectMentions: 1,
      allowHashtags: false,
      allowLinks: false,
      allowUnverifiedClaims: false,
    },
    originalPostRules: {
      preferredLength: "short_to_medium",
      requireExperienceOrSpecificInsight: true,
      allowHashtags: false,
      avoidGreetingIntro: true,
    },
    prohibitedExpressions: [
      "勉強になります",
      "参考になります",
      "本当にその通りです",
      "詳しくはプロフィールへ",
      "自分のサービスなら解決できます",
      "完全自動化すればよい",
    ],
    coreChecks: [
      "AIツール開発者らしい内容か",
      "実際の開発・検証経験を使えるか",
      "他のAI発信者でも書ける一般論になっていないか",
    ],
    version: 1,
    isActive: true,
  },
};
